using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;  // for NotMapped attribute
using Microsoft.AspNetCore.Mvc;                      // for Remote attribute

namespace Registration.Models
{
    public class Customer
    {
        public int ID { get; set; }  // will be autogenerated by database

        [Required(ErrorMessage = "Please enter a username.")]
        //[RegularExpression("^[a-zA-Z0-9 ]+$",
        //    ErrorMessage = "Username may not contain special characters.")]
        [RegularExpression("^[a-zA-Z0-9 ]+$")]
        public string Username { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter an email address.")]
        [Remote("CheckEmail", "Validation")]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a date of birth.")]
        [MinimumAge(13, ErrorMessage = "You must be at least 13 years old.")]
        public DateTime? DOB { get; set; }

        [Required(ErrorMessage = "Please enter a password.")]
        [Compare("ConfirmPassword")]
        [StringLength(25,
            ErrorMessage = "Please limit your password to 25 characters.")]
        public string Password { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please confirm your password.")]
        [Display(Name = "Confirm Password")]
        [NotMapped]
        public string ConfirmPassword { get; set; } = string.Empty;
    }
}